### ISSUE TITLE
Accessing internal `reader` bytes as a Rocket TempFile + others

### ISSUE THREAD

**Issue by raif-s-naffah** [the10thWiz/rocket-multipart#1]
hi Matthew,

first off, thanks for fixing the spelling and publishing 0.2.0!

while the crate works as advertized, and i was able to do what i need so far, i'm not sure i'm doing it the right/best way and would greatly appreciate your input + Rocket expertise.

specifically i need to process some Parts[^1]...

* as JSON serialized types, and others,
* as temporary files potentially to be persisted.

my doubts stem from the fact that i'm implementing those functionalities by consuming the part's contents[^2] which sort of negates the benefit of using a streaming API to process the request.

for the first case i see a [crate][3] that seems to be able to deserialize directly from a stream.  i don't know though if making `reader` public (a) would allow wiring it to that library, and most importantly (b) how such use can affect Rocket request life-cycle if/when the deserialization fails.

alternatively is there a way of using existing, or similar, Rocket capabilities like [JSON as a Form guard][4] and [TempFiles][1] for the parts' contents?  unless of course those functionalities do not operate on streams.

also the ability to customize some sort of _Constraints_ incl. _Size Limit_ on incoming whole requests or parts thereof, which is indirectly used in `MultipartReader::from_data`, would be nice to have.

cheers;

[1]: <https://api.rocket.rs/v0.5/rocket/fs/enum.TempFile>
[2]: <https://docs.rs/tokio/latest/tokio/io/trait.AsyncReadExt.html>
[3]: <https://docs.rs/serde_stream/1.0.1/serde_stream/tokio_stream/trait.SerdeRead.html>
[4]: <https://api.rocket.rs/v0.5/rocket/serde/json/struct.Json#form-guard>

[^1]: instances of `MultipartReadSection<'r, 'a>`.
[^2]: more accurately the `reader` field &mdash;an instance of `&'a mut MultipartReader<'r>`&mdash; w/ the [`read_to_end()`][2] method of its `AsyncReadExt` Trait.

**Comment by the10thWiz** [comment]
It depends on your use case. For JSON, I would likely recommend using `read_to_end` (or `read_to_string`) to create an owned buffer, and use `serde_json`'s `from_bytes` to parse it. JSON isn't really a streamable format (the crate you link converts a stream of bytes into a stream of JSON objects, by parsing each, more or less doing the same as I suggested). It would probably be a good idea to provide a `read_bytes` method, that extracts the entire stream as a `Bytes` object, since this should avoid at least one copy of the data. No matter what, you likely can't avoid buffering the entire JSON object in memory.

For temporary files, you might be better off using `tokio::io::copy_buf`, to copy the full contents directly to a temporary file, avoiding the need to buffer it in memory. This is pretty much what Rocket's `TempFile` does - it copies the entire stream to disk, and provides you with the file path (wrapped in an object with convenient methods, that also deletes the file on drop).

```rust
while let Some(mut section) = stream.next().await.unwrap() {
    if section.content_type() == Some(ContentType::Json) {
        let mut buffer = vec![];
        section.read_to_end(&mut buffer).await.unwrap();
        let obj = serde_json::from_bytes(&buffer).unwrap();
        // Use object
    } else {
        let mut file = tokio::fs::File::open("/tmp/whatever").await.unwrap();
        tokio::io::copy_buf(&mut section, &mut file).await.unwrap();
        // Maybe persist? (Otherwise delete when you're done)
    }
}
```

Ideally, I'd love to be able to support any `FromData` type, but I don't have the ability to construct a `Request` or `Data` object to make it work. I do think some enhancements could help this - some kind of `TempFile` support (although I cannot construct Rocket's `TempFile`), along with some JSON support.

As far as making the `reader` public - no, it wouldn't help. Although `MultipartReader::stream` does implement `Stream`, it doesn't actually return Sections, it returns lower level information. It's really more of an implementation detail. For that reason, I don't plan on ever making `reader` (or any of the currently private fields) public. However, I think there is some real value to the suggestions you provided.

Finally, I made the size limit (of the whole stream) configurable in my most recent push, but I haven't published it yet. If you're interested, I could add another size limit, for the individual sections, but I think the overall size limit is likely good enough.

**Comment by raif-s-naffah** [comment]
thanks Matthew for your prompt response!

for the JSON stuff i'm using...
```rust
let mut buf = vec![];
part.read_to_end(&mut buf).await.unwrap();
let t = serde_json::from_slice::<T>(&buf)?
```
btw, my `part` is your `section`.

and for the file stuff...
```rust
let mut buf = vec![];
part.read_to_end(&mut buf).await.unwrap();
let mut file = File::create(path).await.unwrap();
file.write_all(&buf).await.unwrap();
```
using...
```rust
let mut file = File::create(path).await.unwrap();
copy_buf(&mut part, &mut file).await.unwrap()
```
ends up writing 0 bytes to `file`.  i'll have to dig deeper to understand what's happening; may be the `part` is being dropped before the file is written?

re. the _size limit_ constraint and for PUT + POST handlers i only need to know if there's one _before_ proceeding w/ the request so then i can compare that limit against the value of the content-length header if one was sent.

for now i'll use a `const` that i'll set manually.

thank you for your time + cheers;

**Comment by raif-s-naffah** [comment]
just updated to 0.2.1 and the `to_bytes()` is sweet!

the JSON stuff is now a breeze
```rust
let t = part.json::<T>().await?;
```
my problem w/ the file stuff mentioned in my previous post was my bad.  it's fixed now.

haven't tried the `file/multipart` limit yet but will soon.

thank you kindly for your work + suggestions.
cheers;
