### ISSUE TITLE
Local dispatch yields different result from real server (long)

### ISSUE THREAD

**Issue by raif-s-naffah** [the10thWiz/rocket-multipart#3]
hi @the10thWiz ,

i'm not sure if this is a specific issue to the multipart crate or a general Rocket one but am hoping you can help me get to the bottom of it.

i'm seeing different behaviours for the same handler when exercised locally versus called externally.

the handler has the following signature:
```
#[post("/", data = "<data>", format = "multipart/mixed")]
async fn post_mixed(
    c: Headers,
    data: MultipartReader<'_>,
    db: &State<DB>,
) -> Result<PostResponse, Status> {...}
```
`Headers` is a Request Guard i use to analyze incoming HTTP requests, and the `State<DB>` is a State to pass database connections pool to the handler.

the test looks like so:
```
    let req = client
        .post("/statements")
        .body(body)
        .header(Header::new(header::CONTENT_TYPE.as_str(), "multipart/mixed"));
    let resp = req.dispatch();
```
`client` is an instance of `rocket::local::blocking::Client::tracked()` and `body` is a byte vector that contains the correct sequence for a well-formed multipart contents.

* when called from the outside, the logs show the following:
```
2024-11-02T02:56:50.441559Z  INFO rocket::server: /opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/rocket-0.5.1/src/server.rs:256: POST /statements:
2024-11-02T02:56:50.441585Z ERROR rocket::server::_: /opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/rocket-0.5.1/src/server.rs:348: No matching routes for POST /statements.
2024-11-02T02:56:50.441601Z  WARN rocket::server::_: /opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/rocket-0.5.1/src/server.rs:373: Responding with registered (not_found) 404 catcher.
```
* when called from the test, the output shows:
```
POST /statements multipart/mixed:
   >> Matched: (post_mixed) POST /statements/ multipart/mixed
   >> Data guard `MultipartReader < '_ >` failed: BoundaryNotSpecified.
   >> Outcome: Error(400 Bad Request)
   >> Responding with registered (bad_request) 400 catcher.
```

the tests' outcome is the one i was expecting/hoping the server would behave.  however it's returning 404 instead of 400.

any suggestions as to the cause of this difference?  and most importantly, is there a fix or a work-around?

TIA + cheers;
rsn

**Comment by the10thWiz** [comment]
I did some testing locally, and it seems like both return 400, like you expect, since their Content-Type doesn't specify a boundary to use when parsing the request.

However, there are a few things I would look at. First, what does your external request look like? If you don't set the Content-Type header to `multipart/mixed`, it won't match the `post_mixed` handler. I used the following curl command (which doesn't have a body specified, but since the Content-Type doesn't specify a boundary, it never reads it anyway).

```bash
curl --request POST http://localhost:8000/statements --header 'Content-Type: multipart/mixed' 
```

The example executable I used looks like this:

```
#[post("/", data = "<data>", format = "multipart/mixed")]
async fn post_mixed(
    data: MultipartReader<'_>,
) -> Result<String, Status> {
    todo!()
}

#[launch]
fn rocket() -> _ {
    rocket::build().mount("/statements", routes![post_mixed])
}
```

I omitted the `Headers` and `State<DB>` since the logs indicate they are not rejecting the request in your situation.

**Comment by raif-s-naffah** [comment]
hi @the10thWiz,

thanks for taking the time to look into this.  much appreciated!

your `curl` command made me go back and look more thoroughly at the logs and i'm now able to replicate the behaviour i described.

if you add a semi-colon to the end of the MIME header; i.e. `--header 'Content-Type: multipart/mixed;` you should see Rocket returns `404`.

off the top of my head i dont know if this is valid HTML header syntax or not so i have to go back and check.

**Comment by the10thWiz** [comment]
I'm going to close this issue, since this isn't related to rocket-multipart. I did some quick testing, and adding the semicolon to the test results in the same behavior as your external test. In fact, `MediaType::from_str("multipart/mixed;")` fails to parse, which would explain why Rocket ignores the handler.

After taking a look at the RFC for Content-Type (https://datatracker.ietf.org/doc/html/rfc2045#section-5.1), it looks like this is technically invalid syntax, although if you're aware of any existing clients that produce a trailing semicolon, feel free to open an issue against Rocket.
